---
title: "Murray"
author: "David C. King"
date: "10/25/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(Matrix) # for readMM (sparse matrix of counts)
library(Seurat)
library(dplyr)
library(biomaRt)
library(ggplot2)


DATADIR="./murray_data"
stopifnot(dir.exists(DATADIR))

baseurl = "https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126954"
#                    https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE126954
# download data from https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM3618673 into DATADIR
# you need:
#  GSE126954_gene_by_cell_count_matrix.txt
#  GSE126954_gene_annotation.csv
#  GSE126954_cell_annotation.csv

gene_by_cell_count_matrix_path = file.path(DATADIR, "GSE126954_gene_by_cell_count_matrix.txt.gz")
gene_annotation_path = file.path(DATADIR, "GSE126954_gene_annotation.csv.gz")
cell_annotation_path = file.path(DATADIR, "GSE126954_cell_annotation.csv.gz")


gene_by_cell_count_matrix_url = 'https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE126954&format=file&file=GSE126954_gene_by_cell_count_matrix.txt.gz'
gene_annotation_url = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE126954&format=file&file=GSE126954_gene_annotation.csv.gz"
cell_annotation_url = "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE126954&format=file&file=GSE126954_cell_annotation.csv.gz"

if (TRUE) # download to DATADIR
{
  if (!file.exists(gene_by_cell_count_matrix_path)) {
    download.file(gene_by_cell_count_matrix_url, gene_by_cell_count_matrix_path)
  }
  if (!file.exists(gene_annotation_path)) {
    download.file(gene_annotation_url,gene_annotation_path)
  }
  if (!file.exists(cell_annotation_path)) {
    download.file(cell_annotation_url,cell_annotation_path)
  }
}

```

```{r data}

cell_annot = read.table(
  gzfile(cell_annotation_path),
  sep = ",",
  header = T
)
# drop X, it is identical to "cell"
cell_annot$X = NULL

gene_annot = read.table(
  gzfile(gene_annotation_path),
  sep = ",",
  header = T
)
# drop X, it is identical to "id"
gene_annot$X = NULL
```

```{r data-count-matrix}
glimpse(cell_annot)
glimpse(gene_annot)
#counts = readMM(file = file.path(DATADIR,"GSE126954_gene_by_cell_count_matrix.txt"))
counts = readMM(gzfile(gene_by_cell_count_matrix_path))

#counts@Dimnames <- list(gene_annot$gene_short_name, cell_annot$cell)
# above just fucking stopped working
colnames(counts) <- cell_annot$cell
rownames(counts) <- gene_annot$gene_short_name
system.time({
  murray = CreateSeuratObject(counts, project="Packer 2019", meta.data = cell_annot)
  })  #   user  system elapsed 
      # 18.322  11.663  34.657
#rm(counts)
murray<-SetIdent(murray, value=cell_annot$cell.subtype)
murray$cell.subtype = cell_annot$cell.subtype
murray$cell.type = cell_annot$cell.type
VlnPlot(murray, features = c("nFeature_RNA", "nCount_RNA"))
```


```{r mitochrondial-gene-filter}
# get filternames from https://parasite.wormbase.org/biomart/martview
mart <- useMart("parasite_mart", dataset = "wbps_gene", host = "https://parasite.wormbase.org", port = 443)
genes.df <- getBM(mart = mart, 
      filters = c("species_id_1010", "chromosome_name"),
      value = list("caelegprjna13758", "MtDNA"),
      attributes = c('wbps_gene_id','external_gene_id', 'chromosome_name')
      )

mitoList = genes.df[genes.df$chromosome_name == 'MtDNA','external_gene_id' ] # only 12
genes.df$chromosome_name = NULL # free a little memory
mitoIndices = which(rownames(murray) %in% mitoList)
murray[["percent.mt"]] <- PercentageFeatureSet(murray, features = mitoIndices)
VlnPlot(murray, features = c("nFeature_RNA", "nCount_RNA","percent.mt"))
```

```{r murray-intestine-subtype-markers}
#c("Intestine_middle_and_posterior", "Intestine_anterior","Intestine_far_posterior")
#rownames(murray) <- rownames(murray@assays$RNA@counts) # error?


# all.genes = rownames(murray)
# 
# murray <- NormalizeData(murray, normalization.method = "LogNormalize", scale.factor = 10000)
# system.time({
#   murray = ScaleData(murray, features = all.genes, verbose = T)
# }) #    user   system  elapsed 
#    # 105.307  926.281 4854.311
#    #                > 4854/60
#    #                  [1] 80.9
# 
# murray = FindVariableFeatures(murray, selection.method = "vst", nfeatures = 2000)
# VariableFeatures(murray) %>% head()
# 
# markers.far_posterior = FindMarkers(murray,  
#                                     ident.1="Intestine_far_posterior",
#                                     ident.2 = c("Intestine_middle_and_posterior",
#                                                 "Intestine_anterior"))
# markers.far_posterior$cell.subtype = "Intestine_far_posterior"
# markers.far_posterior$gene = rownames(markers.far_posterior)
# 
# markers.middle_and_posterior = FindMarkers(murray, 
#                                 ident.1="Intestine_middle_and_posterior",
#                                 ident.2 = c("Intestine_far_posterior",
#                                             "Intestine_anterior"))
# 
# markers.middle_and_posterior$cell.subtype = "Intestine_middle_and_posterior"
# markers.middle_and_posterior$gene = rownames(markers.middle_and_posterior)
# 
# 
# markers.anterior = FindMarkers(murray,  
#                                ident.1="Intestine_anterior", 
#                                ident.2 = c("Intestine_far_posterior",
#                                            "Intestine_middle_and_posterior"))
# markers.anterior$cell.subtype = "Intestine_anterior"
# markers.anterior$gene = rownames(markers.anterior)
# 
# 
# markers.intestine_subtypes = rbind(markers.anterior,markers.middle_and_posterior,markers.far_posterior)
# markers.intestine_subtypes$gene = rownames(markers.intestine_subtypes)
# 
# markers.intestine_subtypes %>% group_by(cell.subtype) %>% top_n(n = 10, wt = avg_log2FC) -> top10
# 
# # need to run the intestine subset (currently below)
# DoHeatmap(intestine, features = top10$gene) 
# ggsave("murray_subintestine_markers.pdf", width=10, height=7)
```



```{r rob-data}
rob = readRDS("emb_int.rds")
rob$source = "rob"
murray$source = "murray"

rob$cell.subtype = factor(rob$seurat_clusters, 
                          levels=c(levels(rob$seurat_clusters),
                                   unique(murray$cell.subtype)))

murray$cell.subtype = factor(murray$cell.subtype, 
                             levels=c(unique(murray$cell.subtype),
                                      levels(rob$seurat_clusters)))

rob$cell.type = factor(rob$seurat_clusters, 
                          levels=c(levels(rob$seurat_clusters),
                                   unique(murray$cell.type)))


murray$cell.type = factor(murray$cell.type, 
                          levels=c(unique(murray$cell.type),
                                   levels(rob$seurat_clusters)))


#intestine$cell.subtype = factor(intestine$cell.subtype, levels=c(levels(rob$seurat_clusters),c("Intestine_middle_and_posterior", "Intestine_anterior","Intestine_far_posterior")))

```

```{r rob-to-non-intestine}
non_intestine_idents = levels(murray$cell.subtype)[-grep("Intestine", levels(murray$cell.subtype))]

# remove the added numeric clusters from this list so we don't request Rob's cluster cells from the murray data
non_intestine_idents = non_intestine_idents[-grep("^[0-9]$", non_intestine_idents)]

# NOTE!!!! this subsetting also remove 40523 NAs
non_intestine = subset(murray, idents = non_intestine_idents)
non_intestine$source = "Murray"
non_intestine = NormalizeData(non_intestine)
non_intestine = FindVariableFeatures(non_intestine, selection.method = "vst", nfeatures = 2000)

non_intestine.anchors = FindIntegrationAnchors(object.list=list(rob=rob,murray=non_intestine), dim=1:30)
non_intestine.integrated <- IntegrateData(anchorset = non_intestine.anchors, dims = 1:30)
DefaultAssay(non_intestine.integrated) <- "integrated"
non_intestine.integrated <- ScaleData(non_intestine.integrated, verbose = FALSE)
non_intestine.integrated <- RunPCA(non_intestine.integrated, npcs = 30, verbose = FALSE)
non_intestine.integrated <- RunUMAP(non_intestine.integrated, reduction = "pca", dims = 1:30, verbose = FALSE)
```



```{r plot-non-intestine-rob}
p1 = DimPlot(non_intestine.integrated, reduction = "umap", group.by = "source", label = TRUE, repel = TRUE) + ggtitle("Rob:Murray Integration (non_intestine only)")
p2 = DimPlot(non_intestine.integrated, reduction = "umap", group.by = "cell.subtype", label = TRUE, repel = TRUE) + ggtitle("clusters/cell subtype labelled")
p1
```

```{r intestine}

#intestine.barcodes = WhichCells(murray, idents = c("Intestine_middle_and_posterior", "Intestine_anterior","Intestine_far_posterior"))
intestine = subset(murray, idents = c("Intestine_middle_and_posterior", "Intestine_anterior","Intestine_far_posterior"))
# https://satijalab.org/seurat/articles/integration_mapping.html
intestine$source = "Murray"
intestine = NormalizeData(intestine)
intestine = ScaleData(intestine, features = rownames(intestine))
intestine = FindVariableFeatures(intestine, selection.method = "vst", nfeatures = 2000)


#intestine$cell.subtype = factor(intestine$cell.subtype, levels=c(levels(rob$cell.subtype)))
# intestine.anchors = FindIntegrationAnchors(object.list=list(rob=rob,murray=intestine), dim=1:30)
# intestine.integrated <- IntegrateData(anchorset = intestine.anchors, dims = 1:30)
# 
# 
# DefaultAssay(intestine.integrated) <- "integrated"
# intestine.integrated <- ScaleData(intestine.integrated, verbose = FALSE)
# intestine.integrated <- RunPCA(intestine.integrated, npcs = 30, verbose = FALSE)
# intestine.integrated <- RunUMAP(intestine.integrated, reduction = "pca", dims = 1:30, verbose = FALSE)


intestine <- RunPCA(intestine, npcs = 30, verbose = FALSE)
markers.far_posterior = FindMarkers(intestine,
                                    ident.1="Intestine_far_posterior",
                                    ident.2 = c("Intestine_middle_and_posterior",
                                                "Intestine_anterior"))
markers.far_posterior$cell.subtype = "Intestine_far_posterior"
markers.far_posterior$gene = rownames(markers.far_posterior)

markers.middle_and_posterior = FindMarkers(intestine,
                                ident.1="Intestine_middle_and_posterior",
                                ident.2 = c("Intestine_far_posterior",
                                            "Intestine_anterior"))

markers.middle_and_posterior$cell.subtype = "Intestine_middle_and_posterior"
markers.middle_and_posterior$gene = rownames(markers.middle_and_posterior)


markers.anterior = FindMarkers(intestine,
                               ident.1="Intestine_anterior",
                               ident.2 = c("Intestine_far_posterior",
                                           "Intestine_middle_and_posterior"))
markers.anterior$cell.subtype = "Intestine_anterior"
markers.anterior$gene = rownames(markers.anterior)


markers.intestine_subtypes = rbind(markers.anterior,markers.middle_and_posterior,markers.far_posterior)

markers.intestine_subtypes %>% group_by(cell.subtype) %>% top_n(n = 15, wt = avg_log2FC) -> top15

markers.intestine_subtypes %>% group_by(cell.subtype) %>% filter(grepl("clec*",gene), p_val_adj < .01) %>% top_n(n=15, wt=avg_log2FC) -> top15clecs
             
# need to run the intestine subset (currently below)
DoHeatmap(intestine, features = top15$gene,raster=F)
ggsave("murray_subintestine_markers.pdf", width=10, height=7)

DoHeatmap(intestine, features = top15clecs$gene,raster=F)
ggsave("clec_murray_subintestine_markers.pdf", width=10, height=7)

```


```{r plot-umaps}
p0 = DimPlot(rob, reduction = "umap", label = "TRUE", label.box = TRUE) + ggtitle("Rob data with 10 clusters")
p1 = DimPlot(intestine.integrated, reduction = "umap", group.by = "source", label = TRUE, repel = TRUE) + ggtitle("Rob:Murray Integration (intestine only)")
p2 = DimPlot(intestine.integrated, reduction = "umap", group.by = "cell.subtype", label = TRUE, repel = TRUE) + ggtitle("clusters/cell subtype labelled")
#p3 = DimPlot(intestine.integrated, reduction = "umap", group.by = "cell.subtype", label = TRUE, repel = TRUE) + NoLegend()
p0 + p1+ p2
ggsave("integrated_umaps.pdf", width=20, height=7)
```

```{r rob-vs-whole-murray}
murray = NormalizeData(murray)
murray = FindVariableFeatures(murray, selection.method = "vst", nfeatures = 2000)

# done in rob-data chunk now
#murray$cell.subtype = factor(murray$cell.subtype, levels=c(unique(murray$cell.subtype),c("0",  "1",  "2",  "3",  "4",  "5",  "6",  "7",  "8",  "9")))



wholeset.anchors = FindIntegrationAnchors(object.list=list(rob=rob,murray=murray), dim=1:30)
wholeset.integrated <- IntegrateData(anchorset = wholeset.anchors, dims = 1:30)


DefaultAssay(wholeset.integrated) <- "integrated"
wholeset.integrated <- ScaleData(wholeset.integrated, verbose = FALSE)
wholeset.integrated <- RunPCA(wholeset.integrated, npcs = 30, verbose = FALSE)
wholeset.integrated <- RunUMAP(wholeset.integrated, reduction = "pca", dims = 1:30, verbose = FALSE)

p1=DimPlot(wholeset.integrated, reduction = "umap", group.by = "source", label = TRUE, repel = TRUE) + ggtitle("Rob:Murray Integration")
p2=DimPlot(wholeset.integrated, reduction = "umap", group.by = "cell.type", label = TRUE, repel = TRUE) + ggtitle("clusters/cell subtype labelled")
p2
```

```{r}
p1=DimPlot(wholeset.integrated, reduction = "umap", group.by = "source", label = TRUE, repel = TRUE) + ggtitle("Rob:Murray Integration")
p2=DimPlot(wholeset.integrated, reduction = "umap", group.by = "cell.type", label = TRUE, repel = TRUE) + ggtitle("clusters/cell subtype labelled")
p2
```
